In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Importing the dataset
from google.colab import drive

In [3]:
drive.mount('/content/drive/')

Mounted at /content/drive/


In [4]:
df=pd.read_csv("/content/drive/MyDrive/Data project/heart failure.csv")
df.head()

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0  75.0        0                       582         0                 20   
1  55.0        0                      7861         0                 38   
2  65.0        0                       146         0                 20   
3  50.0        1                       111         0                 20   
4  65.0        1                       160         1                 20   

   high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
0                    1  265000.00               1.9           130    1   
1                    0  263358.03               1.1           136    1   
2                    0  162000.00               1.3           129    1   
3                    0  210000.00               1.9           137    1   
4                    0  327000.00               2.7           116    0   

   smoking  time  DEATH_EVENT  
0        0     4            1  
1        0     6            1  
2        1     7            1  
3        0     7            1  
4        0     8            1

In [5]:
df.shape

(299, 13)

In [6]:
df.isnull().sum()

age                         0
anaemia                     0
creatinine_phosphokinase    0
diabetes                    0
ejection_fraction           0
high_blood_pressure         0
platelets                   0
serum_creatinine            0
serum_sodium                0
sex                         0
smoking                     0
time                        0
DEATH_EVENT                 0
dtype: int64

In [7]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(df.drop('DEATH_EVENT',axis=1), df[['DEATH_EVENT']], random_state=1,train_size=.70)

In [8]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()

In [9]:
dt.fit(xtrain, ytrain)

DecisionTreeClassifier()

In [10]:
#let's predict
pred = dt.predict(xtrain) #training accuracy
pred

array([0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1])

In [11]:
ytrain['Pred'] = pred

In [12]:
ytrain.head(10)

DEATH_EVENT  Pred
14             0     0
210            0     0
236            0     0
44             1     1
163            1     1
292            0     0
117            0     0
258            0     0
41             1     1
79             0     0

In [13]:
pred2 = dt.predict(xtest)
pred2 #testing result

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1])

In [14]:
ytest['pred2'] = pred2
ytest

DEATH_EVENT  pred2
173            0      0
287            0      0
51             1      0
146            0      0
214            0      0
..           ...    ...
122            0      0
246            1      0
278            0      0
251            0      0
19             1      1

[90 rows x 2 columns]

In [15]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from sklearn.metrics import RocCurveDisplay


In [17]:
classification_report(ytest['DEATH_EVENT'], pred2)
print(classification_report(ytest['DEATH_EVENT'], pred2))

              precision    recall  f1-score   support

           0       0.84      0.88      0.85        64
           1       0.65      0.58      0.61        26

    accuracy                           0.79        90
   macro avg       0.74      0.73      0.73        90
weighted avg       0.78      0.79      0.78        90



In [18]:
cm=confusion_matrix(ytest['DEATH_EVENT'], pred2)
cm

array([[56,  8],
       [11, 15]])

In [20]:
tp, fp, fn, tn = confusion_matrix(ytest['DEATH_EVENT'], pred2).reshape(-1)

In [21]:
tp

56

In [22]:
fp

8

In [23]:
fn

11

In [24]:
tn

15

#Assignment

In [25]:
recall = (tp)/(tp+fn)
recall

0.835820895522388

In [26]:
false_positive_rate = (fp)/(fp+tn)
false_positive_rate

0.34782608695652173

In [27]:
specificity = 1-(fp)/(fp+tn)
specificity

0.6521739130434783

In [28]:
precision = (tp)/(tp+fp)
precision

0.875

In [29]:
negative_predictive_value = (tn)/(tn+fn)
negative_predictive_value

0.5769230769230769

In [30]:
threat_score = (tp)/(tp+fn+fp)
threat_score

0.7466666666666667

In [31]:
false_discovery_rate = (fp)/(tp+fp)
false_discovery_rate

0.125

In [32]:
f_measure = (2*precision*recall)/(precision+recall)
f_measure

0.8549618320610687